### ISSUE TITLE
The font size is not saved after exiting the session

### ISSUE THREAD

**Issue by ghost** [intika/org.kde.plasma.digitalclocklite#1]
After setting font size in the widget's settings and exiting the session, it's reset to default. I use Kubuntu 18.04 and KDE 5.12.4.

**Comment by intika** [comment]
the font size is not loaded in the setting pane once you set it and save it, it should remain... 
if you reopen the settings, try to set it once again. before clicking ok. 

can you try to set the size then ok, then logoff and login and let me know if you still have the issue

**Comment by intika** [comment]
also :
1- Do you have saving setting issue with other applets ? 
2- try this and report  
-- set the size 
-- open terminal and run `killall plasmashell ` then  `plasmashell &`
-- report here if its loading the font size when you do that 
3- do you have any cleaning tool running when you loggoff ?

**Comment by ghost** [comment]
1- No, other applets save settings.
2- The font size is reset to default.
3- No.
No matter how I tried to save the size, in any case it's reset to default. I also use the Event Calendar applet and it saves the settings.

**Comment by intika** [comment]
I AM DEBUGGING THE APPLET IGNORE THAT ANSWER I WILL EDIT LATER WITH RIGHTS INFOS
YOU ARE RIGHT THERE IS BUG IN THE APPLET I WILL CORRECT IT AND POST BACK A NEW VERSION... THANKS FOR REPORTING, I WILL LET YOU KNOW... IGNORE THE REST OF THAT ANSWER
 
@sudofail 
In a clean install the applet work, you may have something that block the settings or so... 
Any way here is what you can do... 

**First thing first :** all your desktop is saved to `~/.config/plasma-org.kde.plasma.desktop-appletsrc` make a backup of that file before proceeding applet settings are saved there with different infos

Here is an example 

```
[Containments][2][Applets][342]
immutability=1
plugin=org.kde.plasma.digitalclocklite

[Containments][2][Applets][342][Configuration][ConfigDialog]
DialogHeight=420
DialogWidth=560
```

This mean that i am using 1 applet digitalclocklite assigned with the assigned number 342 ... and the saved settings ... 

**Try to fix :**
1. First make a backup of your file then 
1.1 read point 5
2. you can try to remove all the settings you have for org.kde.plasma.digitalclocklite dont forget to remove the applet configuration section etc... 
3. you can try to edit the settings manually 
4. also you could try with an empty settings file to see if it works with a clean desktop
5. you can do all those test with a new user to avoid missing things

**Comment by intika** [comment]
Just fixed the bug i will upload a new version 
thanks for reporting and testing ;)

**Comment by intika** [comment]
@sudofail done please install last version, from git or kde store its updated everywhere ;) let me know

**Comment by ghost** [comment]
@intika yes, now everything is fine. Thank you!
