### ISSUE TITLE
Overall widget height is not inline with font size

### ISSUE THREAD

**Issue by kirill-gr** [intika/org.kde.plasma.digitalclocklite#3]
I am using vertical panel layout
While font size is set smaller, widget height looks the same as for standard digital clock with large font size
![digital_clock](https://user-images.githubusercontent.com/5472920/57568958-223c3c00-73f7-11e9-8a46-b551593c82fd.png)

**Comment by intika** [comment]
Thanks for reporting this i will fix that on next release ;) and let you know

**Comment by intika** [comment]
for an organization purpose this issue will be followed here https://github.com/Intika-KDE-Plasmoids/plasmoid-digital-clock-lite/issues/4 i will let you know here when it's fixed.
